---
# Define nodeclasses and configuration parameters

#
# Inspect existing nodeclasses, config params and inventory
#
- name: config | Group hosts by defined nodeclasses
  group_by:
    key: scale_nodeclass_{{ item }}
  when: scale_nodeclass is defined
  with_items: "{{ scale_nodeclass }}"

- name: config | Initialize undefined variables
  set_fact:
    scale_config: []
  when: scale_config is undefined

- block:  ## run_once: true
    - name: config | Find existing nodeclasses
      shell: /usr/lpp/mmfs/bin/mmlsnodeclass --user -Y | grep -v HEADER | cut -d ':' -f 7
      register: scale_config_existing_nodeclasses
      changed_when: false
      failed_when: false

    - name: config | Find existing configuration parameters
      shell: /usr/lpp/mmfs/bin/mmlsconfig -Y | grep -v HEADER
      register: scale_config_existing_params
      changed_when: false
      failed_when: false

    - name: config | Find defined nodeclasses
      set_fact:
        scale_config_nodeclasses: "{{ scale_config_nodeclasses | default([]) + [ item ] }}"
      with_items: "{{ groups | select('match', '^scale_nodeclass_.*') | list }}"

    - name: config | Prepare NodeClass files
      vars:
        current_nodeclass: "{{ item | regex_replace('^scale_nodeclass_', '') }}"
      template:
        src: NodeClass.j2
        dest: /var/mmfs/tmp/NodeClass.{{ current_nodeclass }}
      register: scale_config_nodeclassfile
      with_items: "{{ scale_config_nodeclasses | default([]) }}"

#
# Create new nodeclasses
#
    - name: config | Create new nodeclasses
      vars:
        current_nodeclass: "{{ item.item | regex_replace('^scale_nodeclass_', '') }}"
      command: /usr/lpp/mmfs/bin/mmcrnodeclass {{ current_nodeclass }} -N /var/mmfs/tmp/NodeClass.{{ current_nodeclass }}
      when:
        - not current_nodeclass in scale_config_existing_nodeclasses.stdout_lines
        - item is changed
        - item.size > 1
      with_items: "{{ scale_config_nodeclassfile.results }}"

#
# Replace existing nodeclasses
#
    - name: config | Replace existing nodeclasses
      vars:
        current_nodeclass: "{{ item.item | regex_replace('^scale_nodeclass_', '') }}"
      command: /usr/lpp/mmfs/bin/mmchnodeclass {{ current_nodeclass }} replace -N /var/mmfs/tmp/NodeClass.{{ current_nodeclass }}
      when:
        - current_nodeclass in scale_config_existing_nodeclasses.stdout_lines
        - item is changed
        - item.size > 1
      with_items: "{{ scale_config_nodeclassfile.results }}"

#
# Apply config params
#
    - name: config | Apply defined configuration parameters
      vars:
        current_key: "{{ item.1.keys() | list | first }}"
        current_value: "{{ item.1[current_key] | string | regex_replace('True', 'yes') | regex_replace('False', 'no') }}"
        current_nodeclass: "{{ item.0.nodeclass }}"
      command: /usr/lpp/mmfs/bin/mmchconfig {{ current_key }}={{ current_value }} -N {{ current_nodeclass }}
      register: scale_config_changed_params
      when:
        not scale_config_existing_params.stdout | lower is
          search(':' + current_key | lower + ':' + current_value | lower + ':(.+,)?' + current_nodeclass | lower | regex_replace('all', '') + '(,.+)?:')
      with_subelements:
        - "{{ ansible_play_hosts | map('extract', hostvars, 'scale_config') | sum(start=[]) | unique }}"
        - params

    - name: Printing scale_config_changed_params
      debug:
        var: true in scale_config_changed_params.results | map(attribute='changed') | list
    
    - name: Printing scale_daemon_running
      debug:
        var: true in ansible_play_hosts | map('extract', hostvars, 'scale_daemon_running') | list
        
    #################################################################
    # Do shutdown the gpfs cluster

    - name: Check if reboot.storagenodegrp file exists on remote server
      stat:
        path: "/var/mmfs/tmp/reboot.storagenodegrp"
      register: reboot_file_stat
      run_once: true
      
    - name: Create reboot.storagenodegrp if it does not exist
      file:
        path: /var/mmfs/tmp/reboot.storagenodegrp
        state: touch
      when: not reboot_file_stat.stat.exists
      run_once: true
      
    - name: Read the content of NodeClass.storagenodegrp
      command: cat /var/mmfs/tmp/NodeClass.storagenodegrp
      register: node_class_storagenodegrp

    - name: Debug NodeClass.storagenodegrp content
      debug:
        msg: "Content of NodeClass.storagenodegrp: {{ node_class_storagenodegrp.stdout }}"

    - name: Read the content of reboot.storagenodegrp
      command: cat /var/mmfs/tmp/reboot.storagenodegrp
      register: reboot_storagenodegrp

    - name: Debug reboot.storagenodegrp content
      debug:
        msg: "Content of reboot.storagenodegrp: {{ reboot_storagenodegrp.stdout }}"

    - name: Split NodeClass.storagenodegrp content into a list
      set_fact:
        node_class_storagenodegrp_list: "{{ node_class_storagenodegrp.stdout_lines }}"

    - name: Debug NodeClass.storagenodegrp list
      debug:
        msg: "List from node_class_storagenodegrp_list: {{ node_class_storagenodegrp_list }}"

    - name: Split reboot_storagenodegrp content into a list
      set_fact:
        reboot_storagenodegrp_list: "{{ reboot_storagenodegrp.stdout_lines }}"

    - name: Debug reboot.storagenodegrp list
      debug:
        msg: "List from reboot_storagenodegrp_list: {{ reboot_storagenodegrp_list }}"

    - name: Find names unique to NodeClass.storagenodegrp
      set_fact:
        unique_names: "{{ node_class_storagenodegrp_list | difference(reboot_storagenodegrp_list) }}"

    - name: Convert unique names to comma-separated string
      set_fact:
        unique_names_str: "{{ unique_names | join(',') }}"

    - name: Debug unique names
      debug:
        msg: "Unique names: {{ unique_names_str }}"

    - name: Append unique names to reboot.storagenodegrp if not empty
      lineinfile:
        path: /var/mmfs/tmp/reboot.storagenodegrp
        line: "{{ item }}"
      loop: "{{ unique_names }}"
      when: unique_names | length > 0

    - name: Debug final content of reboot.storagenodegrp
      command: cat /var/mmfs/tmp/reboot.storagenodegrp
      register: final_reboot_storagenodegrp_content

    - name: Print final content of reboot.storagenodegrp
      debug:
        msg: "Final content of reboot.storagenodegrp: {{ final_reboot_storagenodegrp_content.stdout }}"
    
    - name: Shutdown gpfs cluster if there are unique names
      command: /usr/lpp/mmfs/bin/mmshutdown -N {{ unique_names_str }}
      register: shutdown_gpfs_cluster
      when: unique_names_str | length > 0

    - name: Wait for 10-second 
      pause:
        seconds: 10
      when: unique_names_str | length > 0
        
    - name: cluster | Startup gpfs cluster
      command: /usr/lpp/mmfs/bin/mmstartup -N {{ unique_names_str }}
      register: started_gpfs_cluster
      when: shutdown_gpfs_cluster.changed == true

    - name: Wait for 10-second 
      pause:
        seconds: 10
      when: started_gpfs_cluster.changed == true

      #################################################################
    - name: config | Check if configuration parameters were changed
      set_fact:
        scale_config_changed: true
      when:
        - true in scale_config_changed_params.results | map(attribute='changed') | list
        - true in ansible_play_hosts | map('extract', hostvars, 'scale_daemon_running') | list
  run_once: true

- block:
    - name: config | Check if ephemeral ports is exists
      command: "{{ scale_command_path }}mmlsconfig tscCmdPortRange"
      register: scale_portrange

    - name: config | Setting ephemeral ports for GPFS daemon communication
      vars:
         ephemeral_ports: "{{ scale_cluster_config.ephemeral_port_range }}"
      command: "{{ scale_command_path }}mmchconfig tscCmdPortRange={{ ephemeral_ports }}"
      when:
         - "'undefined' in scale_portrange.stdout"
      register: scale_portrange_chnage

    - debug:
         msg: "{{ scale_portrange_chnage.cmd }}"
      when: scale_portrange_chnage.cmd is defined
      ignore_errors: yes

  when:
    - scale_cluster_config is defined and scale_cluster_config.ephemeral_port_range is defined
  run_once: true

- block:
    - name: config | Check if numaMemoryInterleave config for s390x is set to yes
      command: "{{ scale_command_path }}mmlsconfig numaMemoryInterleave"
      register: scale_numamemory
      failed_when: false

    - name: config | Setting numaMemoryInterleave config for s390x
      command: "{{ scale_command_path }}mmchconfig numaMemoryInterleave=no"
      when:
         - scale_numamemory.stdout is defined
         - "'yes' in scale_numamemory.stdout"
      register: scale_numamemory_cmd
      failed_when: false

    - debug:
         msg: "{{ scale_numamemory_cmd.cmd }}"
      when: scale_numamemory_cmd.cmd is defined
      ignore_errors: yes
      failed_when: false

  when:
    - ansible_architecture == "s390x"
  ignore_errors: yes
  run_once: true
